/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 13;
  /** RegularExpression Id. */
  int POSDIGIT = 14;
  /** RegularExpression Id. */
  int ZERO = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int IDENT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 11>",
    "<token of kind 12>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
