/* Generated By:JavaCC: Do not edit this line. ExampleConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 5;
  /** RegularExpression Id. */
  int CLOSE = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int EMPTY = 8;
  /** RegularExpression Id. */
  int STAR = 9;
  /** RegularExpression Id. */
  int OR = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "<LETTER>",
    "\"%\"",
    "\"*\"",
    "\"|\"",
  };

}
